config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'home#index'
  resources :choices, :except => [:index, :show, :edit] do
    resources :comments
  end
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  has_many :comments
  validates_presence_of :option_a, :option_b
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :choice
  validates_presence_of :content
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController

  def new
    @choice = Choice.new
  end

  def create
    @choice = Choice.new(choice_params)
    if @choice.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def update
    @choice = Choice.find(params[:id])
    if params[:vote_a] == 'a'
      @choice.update(vote_a: (@choice.vote_a + 1))
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    elsif params[:vote_b] == 'b'
      @choice.update(vote_b: (@choice.vote_b + 1))
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def choice_params
    params.require(:choice).permit(:option_a, :option_b)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @choice = Choice.find(params[:choice_id])
    @comment = @choice.comments.new
  end

  def create
    @choice = Choice.find(params[:choice_id])
    @comment = @choice.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      render :new
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @choices = Choice.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/choices/_form.html.erb
<%= render "layouts/errors", :object => @choice %>

<%= form_for @choice do |f| %>
  <%= f.label :option_a %>
  <%= f.text_field :option_a %>
  <%= f.label :option_b %>
  <%= f.text_field :option_b %>
  <%= f.submit %>
<% end %>

app/views/choices/new.html.erb
<h2>Add a new Choice</h2>

<%= render "form" %>

app/views/choices/new.js.erb
$('#new_choice_link').hide().after('<%= j render("form") %>')

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@choice, @comment] do |f| %>
  <%= f.label :content, "Comment" %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render "form" %>

app/views/comments/new.js.erb
$('#new_comment_link_<%= @choice.id %>').hide().after('<%= j render("form") %>')

app/views/home/index.html.erb
<div id="home">
  <h1>Would You Rather</h1>

  <% @choices.order(created_at: :desc).each do |choice| %>
    <h3>Would you rather?</h3>
    <% if current_user %>
      <p><%= link_to "#{choice.option_a}", choice_path(choice, :vote_a => "a"), class: 'btn-lg btn-a', method: "patch" %>
        OR
        <%= link_to "#{choice.option_b}", choice_path(choice, :vote_b => "b"), class: 'btn-lg btn-b', method: "patch" %>
      </p>
    <% else %>
      <p class="btn btn-a"><%= choice.option_a %></p> OR <p class="btn btn-b"><%= choice.option_b %></p>
    <% end %>

    <div>
      <%= bar_chart [{name: choice.option_a, data: Choice.where(id: choice.id).group(:option_a).sum(:vote_a)}, {name: choice.option_b, data: Choice.where(id: choice.id).group(:option_b).sum(:vote_b)}],  colors: ["pink", "#999"], axes: { y: { label: ''}} %>
    </div>


    <% if choice.comments.any? %>
      <ul>
        <% choice.comments.each do |comment| %>
          <li><%= comment.content %> By: <%= comment.user.email %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No comments yet!</p>
    <% end %>

    <% if current_user %>
      <%= link_to "Add Comment", new_choice_comment_path(choice), id: "new_comment_link_#{choice.id}", class: 'new_comment_link btn-sm btn-warning', remote: true %>
    <% end %>
  <%end %>


  <hr>

  <% if current_user %>
    <%= link_to "Add Choice", new_choice_path, id: 'new_choice_link', remote: true, class: 'btn-lg btn-warning' %>
  <% else %>
    <h2>Sign up to create your own and vote!</h2>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors: </h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WouldYouRather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
  <div class='navbar navbar-default navbar-fixed-bottom'>
    <%= yield(:navbar) %>
    <a class="navbar-brand" href="/">Home</a>
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Log Out #{current_user.email}", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/sign_in">Log In</a></li>
          <li><a href="/users/sign_up">Sign Up</a></li>
        <% end %>
      <ul>
  </div>
<div class="container">

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>


  <%= yield :charts_js %>
  <%= yield %>


</div>
</body>
</html>